//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileFx.AgileModeler.DslPackage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "models";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"AgileModeler";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"AgileHead";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AgileModelerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AgileModelerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AgileModelerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AgileModelerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAgileModelerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AgileModelerCommandSetId), 0x0001);
	
		// Package identifier
		public const string AgileModelerPackageId = "17c24251-0810-4e51-8cf8-c24f0dd3cab4";
		
		// Editor factory identifier
		public const string AgileModelerEditorFactoryId = "c6695f5c-9f44-4b0d-af6f-04138f6a1546";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AgileModelerModelExplorerToolWindowId = "fd722530-1580-4d4a-8805-2ea0b1e90456";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace AgileFx.AgileModeler.DslPackage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AgileModelerCommandSetId = "3c377eba-e82a-45af-9112-a339092d3d4a";
	}
}