//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainModel AgileModelerDomainModel
	/// Create Models for the AgileFx ORM Framework
	/// </summary>
	[DslDesign::DisplayNameResource("AgileFx.AgileModeler.AgileModelerDomainModel.DisplayName", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("AgileFx.AgileModeler.AgileModelerDomainModel.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("5e23cd82-1d47-4904-92bd-59576494a990")]
	public partial class AgileModelerDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// AgileModelerDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x5e23cd82, 0x1d47, 0x4904, 0x92, 0xbd, 0x59, 0x57, 0x64, 0x94, 0xa9, 0x90);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public AgileModelerDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(NamedElement),
				typeof(ModelRoot),
				typeof(ModelClass),
				typeof(ModelFieldBase),
				typeof(ModelType),
				typeof(ClassModelElement),
				typeof(NavigationProperty),
				typeof(ModelField),
				typeof(Association),
				typeof(Inheritance),
				typeof(ModelRootHasTypes),
				typeof(ClassHasFields),
				typeof(ClassHasNavigationProperties),
				typeof(ClassDiagram),
				typeof(AssociationConnector),
				typeof(InheritanceConnector),
				typeof(ClassShape),
				typeof(global::AgileFx.AgileModeler.FixUpDiagram),
				typeof(global::AgileFx.AgileModeler.DecoratorPropertyChanged),
				typeof(global::AgileFx.AgileModeler.ConnectorRolePlayerChanged),
				typeof(global::AgileFx.AgileModeler.CompartmentItemAddRule),
				typeof(global::AgileFx.AgileModeler.CompartmentItemDeleteRule),
				typeof(global::AgileFx.AgileModeler.CompartmentItemRolePlayerChangeRule),
				typeof(global::AgileFx.AgileModeler.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::AgileFx.AgileModeler.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(NamedElement), "Name", NamedElement.NameDomainPropertyId, typeof(NamedElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "Namespace", ModelRoot.NamespaceDomainPropertyId, typeof(ModelRoot.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "ConnectionString", ModelRoot.ConnectionStringDomainPropertyId, typeof(ModelRoot.ConnectionStringPropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "DataContextName", ModelRoot.DataContextNameDomainPropertyId, typeof(ModelRoot.DataContextNamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "TableName", ModelClass.TableNameDomainPropertyId, typeof(ModelClass.TableNamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelClass), "DerivesOrImplements", ModelClass.DerivesOrImplementsDomainPropertyId, typeof(ModelClass.DerivesOrImplementsPropertyHandler)),
				new DomainMemberInfo(typeof(ModelFieldBase), "Getter", ModelFieldBase.GetterDomainPropertyId, typeof(ModelFieldBase.GetterPropertyHandler)),
				new DomainMemberInfo(typeof(ModelFieldBase), "Setter", ModelFieldBase.SetterDomainPropertyId, typeof(ModelFieldBase.SetterPropertyHandler)),
				new DomainMemberInfo(typeof(ModelFieldBase), "IsEdited", ModelFieldBase.IsEditedDomainPropertyId, typeof(ModelFieldBase.IsEditedPropertyHandler)),
				new DomainMemberInfo(typeof(ClassModelElement), "Description", ClassModelElement.DescriptionDomainPropertyId, typeof(ClassModelElement.DescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "Multiplicity", NavigationProperty.MultiplicityDomainPropertyId, typeof(NavigationProperty.MultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "Association", NavigationProperty.AssociationDomainPropertyId, typeof(NavigationProperty.AssociationPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "Type", NavigationProperty.TypeDomainPropertyId, typeof(NavigationProperty.TypePropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "IsForeignkey", NavigationProperty.IsForeignkeyDomainPropertyId, typeof(NavigationProperty.IsForeignkeyPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "ForeignkeyColumn", NavigationProperty.ForeignkeyColumnDomainPropertyId, typeof(NavigationProperty.ForeignkeyColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "IsPrimaryKey", ModelField.IsPrimaryKeyDomainPropertyId, typeof(ModelField.IsPrimaryKeyPropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "DatabaseColumnName", ModelField.DatabaseColumnNameDomainPropertyId, typeof(ModelField.DatabaseColumnNamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "DefaultValue", ModelField.DefaultValueDomainPropertyId, typeof(ModelField.DefaultValuePropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "Nullable", ModelField.NullableDomainPropertyId, typeof(ModelField.NullablePropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "Type", ModelField.TypeDomainPropertyId, typeof(ModelField.TypePropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "IsDbGenerated", ModelField.IsDbGeneratedDomainPropertyId, typeof(ModelField.IsDbGeneratedPropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "IsFixedLength", ModelField.IsFixedLengthDomainPropertyId, typeof(ModelField.IsFixedLengthPropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "IsUnicode", ModelField.IsUnicodeDomainPropertyId, typeof(ModelField.IsUnicodePropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "MaxLength", ModelField.MaxLengthDomainPropertyId, typeof(ModelField.MaxLengthPropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "IsIdentity", ModelField.IsIdentityDomainPropertyId, typeof(ModelField.IsIdentityPropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "IsUnique", ModelField.IsUniqueDomainPropertyId, typeof(ModelField.IsUniquePropertyHandler)),
				new DomainMemberInfo(typeof(ModelField), "UpdateCheck", ModelField.UpdateCheckDomainPropertyId, typeof(ModelField.UpdateCheckPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1Multiplicity", Association.End1MultiplicityDomainPropertyId, typeof(Association.End1MultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1RoleName", Association.End1RoleNameDomainPropertyId, typeof(Association.End1RoleNamePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2Multiplicity", Association.End2MultiplicityDomainPropertyId, typeof(Association.End2MultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2RoleName", Association.End2RoleNameDomainPropertyId, typeof(Association.End2RoleNamePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1NavigationProperty", Association.End1NavigationPropertyDomainPropertyId, typeof(Association.End1NavigationPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2NavigationProperty", Association.End2NavigationPropertyDomainPropertyId, typeof(Association.End2NavigationPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "Name", Association.NameDomainPropertyId, typeof(Association.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "ManyToManyMappingTable", Association.ManyToManyMappingTableDomainPropertyId, typeof(Association.ManyToManyMappingTablePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1ManyToManyMappingColumn", Association.End1ManyToManyMappingColumnDomainPropertyId, typeof(Association.End1ManyToManyMappingColumnPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2ManyToManyMappingColumn", Association.End2ManyToManyMappingColumnDomainPropertyId, typeof(Association.End2ManyToManyMappingColumnPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1MultiplicityDisplay", Association.End1MultiplicityDisplayDomainPropertyId, typeof(Association.End1MultiplicityDisplayPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2MultiplicityDisplay", Association.End2MultiplicityDisplayDomainPropertyId, typeof(Association.End2MultiplicityDisplayPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "IsEdited", Association.IsEditedDomainPropertyId, typeof(Association.IsEditedPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1ManyToManyNavigationProperty", Association.End1ManyToManyNavigationPropertyDomainPropertyId, typeof(Association.End1ManyToManyNavigationPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2ManyToManyNavigationProperty", Association.End2ManyToManyNavigationPropertyDomainPropertyId, typeof(Association.End2ManyToManyNavigationPropertyPropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End1ManyToManyFieldName", Association.End1ManyToManyFieldNameDomainPropertyId, typeof(Association.End1ManyToManyFieldNamePropertyHandler)),
				new DomainMemberInfo(typeof(Association), "End2ManyToManyFieldName", Association.End2ManyToManyFieldNameDomainPropertyId, typeof(Association.End2ManyToManyFieldNamePropertyHandler)),
				new DomainMemberInfo(typeof(Inheritance), "Discriminator", Inheritance.DiscriminatorDomainPropertyId, typeof(Inheritance.DiscriminatorPropertyHandler)),
				new DomainMemberInfo(typeof(Inheritance), "DerivedClassPrimaryKeyColumn", Inheritance.DerivedClassPrimaryKeyColumnDomainPropertyId, typeof(Inheritance.DerivedClassPrimaryKeyColumnPropertyHandler)),
				new DomainMemberInfo(typeof(Inheritance), "BaseClassPrimaryKeyColumn", Inheritance.BaseClassPrimaryKeyColumnDomainPropertyId, typeof(Inheritance.BaseClassPrimaryKeyColumnPropertyHandler)),
				new DomainMemberInfo(typeof(ClassDiagram), "Initialized", ClassDiagram.InitializedDomainPropertyId, typeof(ClassDiagram.InitializedPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(Association), "Source", Association.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(Association), "Target", Association.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(Inheritance), "Superclass", Inheritance.SuperclassDomainRoleId),
				new DomainRolePlayerInfo(typeof(Inheritance), "Subclass", Inheritance.SubclassDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasTypes), "ModelRoot", ModelRootHasTypes.ModelRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasTypes), "Type", ModelRootHasTypes.TypeDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasFields), "ModelClass", ClassHasFields.ModelClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasFields), "ModelField", ClassHasFields.ModelFieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasNavigationProperties), "ModelClass", ClassHasNavigationProperties.ModelClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClassHasNavigationProperties), "NavigationProperty", ClassHasNavigationProperties.NavigationPropertyDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12);
				createElementMap.Add(typeof(ModelRoot), 0);
				createElementMap.Add(typeof(ModelClass), 1);
				createElementMap.Add(typeof(ModelFieldBase), 2);
				createElementMap.Add(typeof(NavigationProperty), 3);
				createElementMap.Add(typeof(ModelField), 4);
				createElementMap.Add(typeof(ClassDiagram), 5);
				createElementMap.Add(typeof(AssociationConnector), 6);
				createElementMap.Add(typeof(InheritanceConnector), 7);
				createElementMap.Add(typeof(ClassShape), 8);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::AgileFx.AgileModeler.AgileModelerDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new ModelRoot(partition, propertyAssignments);
				case 1: return new ModelClass(partition, propertyAssignments);
				case 2: return new ModelFieldBase(partition, propertyAssignments);
				case 3: return new NavigationProperty(partition, propertyAssignments);
				case 4: return new ModelField(partition, propertyAssignments);
				case 5: return new ClassDiagram(partition, propertyAssignments);
				case 6: return new AssociationConnector(partition, propertyAssignments);
				case 7: return new InheritanceConnector(partition, propertyAssignments);
				case 8: return new ClassShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(5);
				createElementLinkMap.Add(typeof(Association), 0);
				createElementLinkMap.Add(typeof(Inheritance), 1);
				createElementLinkMap.Add(typeof(ModelRootHasTypes), 2);
				createElementLinkMap.Add(typeof(ClassHasFields), 3);
				createElementLinkMap.Add(typeof(ClassHasNavigationProperties), 4);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::AgileFx.AgileModeler.AgileModelerDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new Association(partition, roleAssignments, propertyAssignments);
				case 1: return new Inheritance(partition, roleAssignments, propertyAssignments);
				case 2: return new ModelRootHasTypes(partition, roleAssignments, propertyAssignments);
				case 3: return new ClassHasFields(partition, roleAssignments, propertyAssignments);
				case 4: return new ClassHasNavigationProperties(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "AgileFx.AgileModeler.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return AgileModelerDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (AgileModelerDomainModel.resourceManager == null)
				{
					AgileModelerDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(AgileModelerDomainModel).Assembly);
				}
				return AgileModelerDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return AgileModelerDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return AgileModelerDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (AgileModelerDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new AgileModelerCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					AgileModelerDomainModel.copyClosure = copyFilter;
				}
				return AgileModelerDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (AgileModelerDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new AgileModelerDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					AgileModelerDomainModel.removeClosure = removeFilter;
				}
				return AgileModelerDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::AgileFx.AgileModeler.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class AgileModelerDeleteClosure : AgileModelerDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public AgileModelerDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class AgileModelerDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public AgileModelerDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::AgileFx.AgileModeler.ModelRootHasTypes.TypeDomainRoleId, true);
			DomainRoles.Add(global::AgileFx.AgileModeler.ClassHasFields.ModelFieldDomainRoleId, true);
			DomainRoles.Add(global::AgileFx.AgileModeler.ClassHasNavigationProperties.NavigationPropertyDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class AgileModelerCopyClosure : AgileModelerCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public AgileModelerCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class AgileModelerCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public AgileModelerCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainEnumeration: AccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum AccessModifier
	{
		/// <summary>
		/// Public
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.AccessModifier/Public.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Public = 0,
		/// <summary>
		/// Private
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.AccessModifier/Private.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Private = 2,
		/// <summary>
		/// Protected
		/// Description for AgileFx.AgileModeler.AccessModifier.Protected
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.AccessModifier/Protected.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Protected = 1,
		/// <summary>
		/// Internal
		/// Description for AgileFx.AgileModeler.AccessModifier.Internal
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.AccessModifier/Internal.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Internal = 3,
	}
}
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainEnumeration: TypeAccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TypeAccessModifier
	{
		/// <summary>
		/// Public
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.TypeAccessModifier/Public.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Public = 0,
		/// <summary>
		/// Private
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.TypeAccessModifier/Private.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Private = 1,
	}
}
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainEnumeration: InheritanceModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum InheritanceModifier
	{
		/// <summary>
		/// None
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.InheritanceModifier/None.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		None = 0,
		/// <summary>
		/// Abstract
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.InheritanceModifier/Abstract.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Abstract = 1,
		/// <summary>
		/// Sealed
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.InheritanceModifier/Sealed.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Sealed = 2,
	}
}
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainEnumeration: Multiplicity
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Multiplicity
	{
		/// <summary>
		/// ZeroMany
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.Multiplicity/ZeroMany.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		ZeroMany = 0,
		/// <summary>
		/// One
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.Multiplicity/One.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		One = 1,
		/// <summary>
		/// ZeroOne
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.Multiplicity/ZeroOne.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		ZeroOne = 2,
	}
}
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainEnumeration: BuiltInTypes
	/// Description for AgileFx.AgileModeler.BuiltInTypes
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum BuiltInTypes
	{
		/// <summary>
		/// Boolean
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Boolean.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Boolean,
		/// <summary>
		/// Byte
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Byte
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Byte.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Byte,
		/// <summary>
		/// DateTime
		/// Description for AgileFx.AgileModeler.BuiltInTypes.DateTime
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/DateTime.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		DateTime,
		/// <summary>
		/// Decimal
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Decimal
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Decimal.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Decimal,
		/// <summary>
		/// Double
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Double
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Double.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Double,
		/// <summary>
		/// Guid
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Guid
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Guid.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Guid,
		/// <summary>
		/// Int16
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Int16
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Int16.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Int16,
		/// <summary>
		/// Int64
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Int64
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Int64.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Int64,
		/// <summary>
		/// Int32
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Int32
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Int32.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Int32,
		/// <summary>
		/// Single
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Single
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Single.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Single,
		/// <summary>
		/// String
		/// Description for AgileFx.AgileModeler.BuiltInTypes.String
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/String.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		String,
		/// <summary>
		/// Binary
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Binary
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Binary.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Binary,
		/// <summary>
		/// Timestamp
		/// Description for AgileFx.AgileModeler.BuiltInTypes.Timestamp
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.BuiltInTypes/Timestamp.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Timestamp,
	}
}
namespace AgileFx.AgileModeler
{
	/// <summary>
	/// DomainEnumeration: ConcurrencyCheckFrequency
	/// Description for AgileFx.AgileModeler.ConcurrencyCheckFrequency
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum ConcurrencyCheckFrequency
	{
		/// <summary>
		/// Always
		/// Description for AgileFx.AgileModeler.ConcurrencyCheckFrequency.Always
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.ConcurrencyCheckFrequency/Always.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Always = 0,
		/// <summary>
		/// WhenChanged
		/// Description for AgileFx.AgileModeler.ConcurrencyCheckFrequency.WhenChanged
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.ConcurrencyCheckFrequency/WhenChanged.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		WhenChanged = 1,
		/// <summary>
		/// Never
		/// Description for AgileFx.AgileModeler.ConcurrencyCheckFrequency.Never
		/// </summary>
		[DslDesign::DescriptionResource("AgileFx.AgileModeler.ConcurrencyCheckFrequency/Never.Description", typeof(global::AgileFx.AgileModeler.AgileModelerDomainModel), "AgileFx.AgileModeler.GeneratedCode.DomainModelResx")]
		Never = 2,
	}
}

